### ISSUE TITLE
OneWire Libary funktionslos auf RP2040

### ISSUE THREAD

**Issue by MNieddu91** [bestfan/HB-UNI-Sen-CO2#1]
Hallo bestfan, 

erst einmal vielen Dank für deine Arbeit, meine 3 Sensoren arbeiten problemlos, allerdings muss ich aktuell auf die Verwendung des eingebauten DS18B20 verzichten, da die OneWire Libary scheinbar nicht auf RP2040 lauffähig ist. 
Wenn ich Zeile 21 //#define useDS18X20 //use temperature sensor auskommentiere bleibt kann ich den Sketch zwar sauber uploaden, jedoch bleibt er dann beim anschalten des Gerätes bei in Zeile 32 in  Sens_DS18X20.h einfach stehen. TEST: DS18x20 init wird noch geprintet, aber dann hängt sich das device auf.

Test Sketche mit der OneWire Libary laufen auch nicht. Scheinbar gibt es hier tatsächlich Probleme mit OneWire und dem RP2040. Wenn ich einen Testscatch aus OneWire flashe, dann kriege ich keine Verbindung mehr über den COM Port auf dem RPi, vielleicht liegt hier auch schon das Problem. Welche Version von OneWire nutzt du denn ? 

Es gibt eine angepasste Libary OneWireNG, welche bei mir funktioniert und mit Testsketch auch Ausgaben für den DS18B20 liefert. Leider reichen meine Kenntnisse jedoch nicht aus diese Anpassung selbst vorzunehmen. 

Hast du ein geeignetes Setup zum testen? Schade wäre es, wenn ich nicht auf den verbauten TempSensor zurückgreifen kann. 

Gerne kann ich dich auch beim debuggen unterstützen, sofern ich irgendwas testen soll. 
Komme gerne einfach auf mich zu. 

UPDATE: [Hier](https://github.com/PaulStoffregen/OneWire/issues/123) wird auch auf das Problem eingegangen und der Verweis zu OneWireNG aufgemacht. 

Viele Grüße
Marco

**Comment by MNieddu91** [comment]
Lösung: 

Folgendes hat mir geholfen, nun erkennt er den DS18B20 https://forum.seeedstudio.com/t/ds18b20-temperature-sensor-issue/263525/5

![image](https://github.com/bestfan/HB-UNI-Sen-CO2/assets/3452678/806ac624-aab8-4437-9ede-8423cc987031)

**Comment by bestfan** [comment]
Hallo Marco,
vielen Dank für das Interesse an dem Projekt und Deine Hinweise zur Behebung des Issues.
Ja, das mit RP2040 und  der OneWire Lib ist nicht so schön. Ich hatte in meinem README geschrieben, dass man die aktuelle "master" Version nehmen sollte. Dort ist in der Datei "util/OneWire_direct_gpio.h" die oben beschriebene Deklaration eingefügt. Wenn das auch durch Editieren der Release-Version funktioniert, umso besser.
Grüße
Stefan
